# Generated by Django 6.0.4 on 2026-05-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono / WhatsApp')),
                ('servicio', models.CharField(max_length=50, verbose_name='Servicio solicitado')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('contactado', 'Contactado'), ('cerrado', 'Cerrado')], default='nueva', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
