# Generated by Django 6.0.4 on 2026-05-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_cotizacion_categoria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
